resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: resource-src
  type: git
  source:
    uri: https://github.com/ljfranklin/terraform-resource
- name: terraform
  type: terraform
  source:
    storage:
      access_key_id:     {{storage_access_key}}
      secret_access_key: {{storage_secret_key}}
      bucket:            {{storage_bucket}}
      bucket_path:       {{storage_bucket}}
      state_file:        terraform-test.tfstate
    terraform:
      source: resource-src/fixtures/aws
      vars:
        access_key:  {{ec2_access_key}}
        secret_key:  {{ec2_secret_key}}
        vpc_id:      {{test_vpc_id}}
        subnet_cidr: 10.0.0.0/24

jobs:
  - name: create-infrastructure
    plan:
      - get: resource-src
      - put: terraform
      - task: show-outputs
        config:
          platform: linux
          inputs:
            - name: terraform
          run:
            path: /bin/sh
            args:
              - -c
              - "cat terraform/metadata"

  - name: update-infrastructure-via-params
    plan:
      - get: resource-src
      - get: terraform
        trigger: true
        passed: [create-infrastructure]
      - put: terraform
        params:
          terraform:
            vars:
              tag_name: "params-terraform-resource-test"

  - name: update-infrastructure-via-file
    plan:
      - get: resource-src
      - get: terraform
        trigger: true
        passed: [update-infrastructure-via-params]
      - task: make-var-file
        config:
          platform: linux
          outputs:
             - name: vars
          run:
            path: /bin/sh
            args:
              - -c
              - "echo 'tag_name: file-terraform-resource-test' > vars/input.yml"
      - put: terraform
        params:
          terraform:
            var_file: vars/input.yml

  - name: destroy-infrastructure
    plan:
      - get: resource-src
      - get: terraform
        trigger: true
        passed: [update-infrastructure-via-file]
      - put: terraform
        params:
          action: destroy
        get_params:
          action: destroy
