resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: resource-src
  type: git
  source:
    uri: https://github.com/ljfranklin/terraform-resource
- name: terraform
  type: terraform
  source:
    access_key_id:     {{storage_access_key}}
    secret_access_key: {{storage_secret_key}}
    bucket:            {{storage_bucket}}
    key:               terraform-test.tfstate

jobs:
  - name: create-infrastructure
    plan:
      - get: resource-src
      - put: terraform
        params: &terraform-params
          terraform_source: resource-src/fixtures/aws
          terraform_vars:
            access_key: {{ec2_access_key}}
            secret_key: {{ec2_secret_key}}

  - name: update-infrastructure
    plan:
      - get: resource-src
      - get: terraform
        trigger: true
        passed: [create-infrastructure]
      - put: terraform
        params:
          <<: *terraform-params
          terraform_vars:
            access_key: {{ec2_access_key}}
            secret_key: {{ec2_secret_key}}
            tag_name: "updated-terraform-resource-test"

  - name: destroy-infrastructure
    plan:
      - get: resource-src
      - get: terraform
        trigger: true
        passed: [update-infrastructure]
      - put: terraform
        params:
          <<: *terraform-params
          action: destroy
