jobs:
  - name: auto-bump-terraform
    plan:
      - get: terraform-github
        trigger: true
      - get: resource-src
      - task: bump-terraform-cli
        file: resource-src/ci/tasks/bump-terraform-cli.yml
      - task: git-commit
        file: resource-src/ci/tasks/git-commit.yml
        input_mapping: {input-src: updated-resource-src}
        output_mapping: {output-src: committed-resource-src}
        params:
          GIT_ADD_ARGS: ./config/terraform-version
          GIT_COMMIT_MSG: ":airplane: Auto-commit: Bumping Terraform CLI version"
          GIT_COMMIT_USERNAME: friendly-ci
          GIT_COMMIT_EMAIL: {{git_commit_email}}
          GIT_SUCCEED_ON_NO_CHANGES: true
      - put: resource-src
        params:
          repository: committed-resource-src/
          rebase: true

  - name: push-dev-image
    plan:
      - get: resource-src
        trigger: true
      - task: build-artifacts
        file: resource-src/ci/tasks/build-dev-artifacts.yml
      - put: terraform-dev-image
        params:
          build: build-artifacts/
          cache: true

  - name: test-unit
    plan:
      - get: resource-src
        trigger: true
        passed: [push-dev-image]
      - task: test-unit
        file: resource-src/ci/tasks/test-unit.yml
        params:
          AWS_ACCESS_KEY:           {{ec2_access_key}}
          AWS_SECRET_KEY:           {{ec2_secret_key}}
          AWS_BUCKET:               {{storage_bucket}}
          AWS_BUCKET_PATH:          terraform-test-unit
          AWS_TEST_VPC_ID:          {{test_vpc_id}}
          S3_COMPATIBLE_BUCKET:     {{s3_compatible_bucket}}
          S3_COMPATIBLE_ENDPOINT:   {{s3_compatible_endpoint}}
          S3_COMPATIBLE_ACCESS_KEY: {{s3_compatible_access_key}}
          S3_COMPATIBLE_SECRET_KEY: {{s3_compatible_secret_key}}
          S3_KMS_KEY_ID:            {{s3_kms_key_id}}

  - name: push-test-image
    plan:
      - get: resource-src
        trigger: true
        passed: [test-unit]
      - task: build-artifacts
        file: resource-src/ci/tasks/build-prod-artifacts.yml
      - put: terraform-test-image
        params:
          build: build-artifacts/
          cache: true

  - name: create-infrastructure
    plan:
      - get: resource-src
        trigger: true
        passed: [push-test-image]
      - put: terraform
        params:
          env_name: terraform-ci
          vars:
            subnet_cidr: 10.0.0.0/24
      - &show-outputs
        task: show-outputs
        config:
          platform: linux
          image_resource: &test-image
            type: docker-image
            source:
              repository: ljfranklin/terraform-resource
              tag: test
          inputs:
            - name: terraform
          run:
            path: /bin/sh
            args:
              - -c
              - |
                  echo "name: $(cat terraform/name)"
                  echo "metadata: $(cat terraform/metadata)"

  - name: update-infrastructure-via-params
    plan:
      - get: resource-src
        trigger: true
        passed: [create-infrastructure]
      - put: terraform
        params:
          env_name: terraform-ci
          vars:
            # update the tag_name for the subnet
            tag_name: "params-terraform-resource-test"
      - *show-outputs

  - name: update-infrastructure-via-file
    plan:
      - get: resource-src
        trigger: true
        passed: [update-infrastructure-via-params]
      - task: make-var-file
        config:
          platform: linux
          image_resource: *test-image
          outputs:
             - name: vars
          run:
            path: /bin/sh
            args:
              - -c
              - |
                  echo 'tag_name: file-terraform-resource-test' >> vars/input.yml
      - put: terraform
        params:
          env_name: terraform-ci
          var_file: vars/input.yml
      - *show-outputs

  - name: destroy-infrastructure
    plan:
      - get: resource-src
        trigger: true
        passed: [update-infrastructure-via-file]
      - put: terraform
        params:
          env_name: terraform-ci
          action: destroy
        get_params:
          action: destroy

  - name: create-env-and-lock
    plan:
      - get: resource-src
        trigger: true
        passed: [push-test-image]
      - put: terraform-remote-src
        params:
          # generate a random env_name for the lock file
          generate_random_name: true
          delete_on_failure: true
          vars:
            subnet_cidr: 10.0.1.0/24
      # create a new lock containing the terraform output
      - put: locks
        params:
          add: terraform-remote-src/

  - name: lock-env
    plan:
      - get: resource-src
        trigger: true
        passed: [create-env-and-lock]
      - put: locks
        params:
          acquire: true
      - task: show-lock
        config:
          platform: linux
          image_resource: *test-image
          inputs:
            - name: locks
          run:
            path: /bin/sh
            args:
              - -c
              - |
                  echo "name: $(cat locks/name)"
                  echo "metadata: $(cat locks/metadata)"

  - name: destroy-env-and-lock
    plan:
      - get: resource-src
        trigger: true
        passed: [lock-env]
      - get: locks
        passed: [lock-env]
      # destroy the IaaS resources
      - put: terraform-remote-src
        params:
          env_name_file: locks/name
          action: destroy
        get_params:
          action: destroy
      # destroy the lock
      - put: locks
        params:
          remove: locks/

  - name: push-prod-image
    plan:
      - get: resource-src
        passed: [destroy-env-and-lock, destroy-infrastructure]
      - put: terraform-prod-image
        params:
          pull_repository: ljfranklin/terraform-resource
          pull_tag: test
          cache: true

resource_types:
- name: terraform
  type: docker-image
  source:
    # use tag `latest` for stable release
    repository: ljfranklin/terraform-resource
    tag: test

resources:
- name: resource-src
  type: git
  source:
    uri: git@github.com:ljfranklin/terraform-resource.git
    branch: master
    private_key: {{git_private_key}}
- name: terraform-github
  type: github-release
  source:
    user: hashicorp
    repository: terraform
- name: terraform-dev-image
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev
    email: {{docker_email}}
    username: {{docker_username}}
    password: {{docker_password}}
- name: terraform-test-image
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: test
    email: {{docker_email}}
    username: {{docker_username}}
    password: {{docker_password}}
- name: terraform-prod-image
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
    email: {{docker_email}}
    username: {{docker_username}}
    password: {{docker_password}}
- name: locks
  type: pool
  source:
    uri: git@github.com:ljfranklin/terraform-resource.git
    branch: ci-pool-test
    pool: aws-ci-pool
    private_key: {{git_private_key}}
- name: terraform
  type: terraform
  source: &terraform-source
    # options common to all jobs can be specified under source
    storage:
      access_key_id:     {{storage_access_key}}
      secret_access_key: {{storage_secret_key}}
      bucket:            {{storage_bucket}}
      bucket_path:       ci-pipeline
    terraform_source: resource-src/fixtures/aws
    vars:
      access_key:  {{ec2_access_key}}
      secret_key:  {{ec2_secret_key}}
      vpc_id:      {{test_vpc_id}}
- name: terraform-remote-src
  type: terraform
  source:
    <<: *terraform-source
    terraform_source: github.com/ljfranklin/terraform-resource//fixtures/aws
